# Keep runtime files outside the repository and clean them on success/failure.
if(DEFINED ENV{TEMP})
    set(temp_root "$ENV{TEMP}")
elseif(DEFINED ENV{TMPDIR})
    set(temp_root "$ENV{TMPDIR}")
else()
    set(temp_root "/tmp")
endif()
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef tag)
set(work "${temp_root}/minidb-recovery-${tag}")
file(MAKE_DIRECTORY "${work}")
function(require_success result label)
    if(NOT "${result}" STREQUAL "0")
        file(REMOVE_RECURSE "${work}")
        message(FATAL_ERROR "${label}: ${result}")
    endif()
endfunction()
foreach(mode dirty installed reset)
    set(db "${work}/${mode}.snapshot")
    execute_process(COMMAND "${HELPER}" "${mode}" "${db}" RESULT_VARIABLE result TIMEOUT 15)
    require_success("${result}" "abrupt writer ${mode}")
    if(mode STREQUAL "dirty")
        set(verify verify-dirty)
    else()
        set(verify verify-saved)
    endif()
    execute_process(COMMAND "${HELPER}" "${verify}" "${db}" RESULT_VARIABLE result TIMEOUT 15)
    require_success("${result}" "reopen ${mode}")
    file(WRITE "${work}/input" "GET b\nGET c\nEXISTS a\nEXIT\n")
    execute_process(COMMAND "${CLI}" "${db}" INPUT_FILE "${work}/input"
        OUTPUT_VARIABLE output ERROR_VARIABLE errors RESULT_VARIABLE result TIMEOUT 15)
    require_success("${result}" "CLI ${mode}: ${errors}")
    foreach(expected "MiniDB> 2" "MiniDB> 3" "MiniDB> false")
        string(FIND "${output}" "${expected}" found)
        if(found EQUAL -1)
            require_success(1 "missing CLI output ${expected}")
        endif()
    endforeach()
    execute_process(COMMAND "${HELPER}" verify-saved "${db}" RESULT_VARIABLE result TIMEOUT 15)
    require_success("${result}" "reopen after CLI exit ${mode}")
endforeach()
file(REMOVE_RECURSE "${work}")
